[package]
name = "iced_test_counter"
version = "0.1.0"
authors = ["Jimmy <jimmy@1024bees.com>"]
edition = "2018"
publish = false

[dependencies]
iced = {git = "https://github.com/1024bees/iced", branch="headless" }


[dev-dependencies]
iced-test = {path = "../.."}
